platform :ios, '13.0'

target 'JefersonHearthstone' do
  use_frameworks!


  pod 'Kingfisher', '~> 6.1.1'
  pod 'Alamofire', '~> 5.4.2'


  target 'JefersonHearthstoneTests' do
    inherit! :search_paths
    pod 'Mockingjay', '~> 3.0.0-alpha.1'
    pod 'Nimble-Snapshots', '~> 9.0.0'
  end

  target 'JefersonHearthstoneUITests' do
    # Pods for testing
  end

end
